version: '3.9'
services:
    airflow:
        container_name: docker-airflow
        build:
            context: .
            dockerfile: Dockerfile
        restart: always

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        env_file:
            - secrets/postgres.env
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: docker-airflow
        restart: always
        depends_on:
            - airflow
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        env_file:
            - secrets/fernet_key.env
            - secrets/postgres.env
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "./dags:${AIRFLOW_DAG_DIR}"
            # - "./plugins:${AIRFLOW_PLUGINS_DIR}"
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    
    redis:
        image: 'redis:5.0.5'
        command: [
            "bash", "-c",
            '
            docker-entrypoint.sh
            --requirepass $${REDIS_PASSWORD}
            '
        ]
        restart: always
        env_file:
            - secrets/redis.env
